<?xml version="1.0" ?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="inertial_macros.xacro"/>

  <!-- Robot's base properties -->
  <xacro:property name="base_length" value="0.21"/>
  <xacro:property name="base_width" value="0.11"/>
  <xacro:property name="base_height" value="0.035"/>

  <!-- Robot's wheel properties -->
  <xacro:property name="wheel_radius" value="0.0325"/>
  <xacro:property name="wheel_height" value="0.025"/>
  <xacro:property name="wheel_mass" value="0.031"/>

  <!-- Distance between centre of wheel and robot base -->
  <xacro:property name="wheel_zoff" value="0.0125"/>

  <link name="base_footprint"/> 	

   <joint name="base_joint" type="fixed">
     <parent link="base_footprint"/>
     <child link="base_link"/>
     <origin xyz="-0.076 0 ${(wheel_radius + wheel_zoff / 2)}" rpy="0 0 0"/>
   </joint>
	
  <!-- Robot base chasis-->
  <link name="base_link">
      <visual>
        <origin xyz="${base_length/2} 0 ${-wheel_zoff}" rpy="0 0 ${pi}"/>
          <geometry>
              <mesh filename="package://robot_description/meshes/robot_chassis.dae" />
          </geometry>
      </visual>
      <collision>
        <origin xyz="${base_length/2} 0 ${-wheel_zoff}" rpy="0 0 0"/>
        <geometry>
          <box size="${base_length} ${base_width} ${base_height}"/>
        </geometry>
      </collision>

    <!-- Caster mount -->
      <visual name="caster_mount_visual">
          <origin xyz="0.0185 0 -0.0475" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://robot_description/meshes/caster_mount.dae" />
        </geometry>
      </visual>
      <collision name="caster_mount_collision">
        <origin xyz="0.0185 0 -0.005" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.023" length="0.0125"/>
        </geometry>
      </collision>

      <!-- Rpi stand -->
      <visual name="rpi_4_stand_visual">
        <origin xyz="0.045 0.015 0.031" rpy="${pi} 0 ${-pi}"/>
          <geometry>
              <mesh filename="package://robot_description/meshes/rpi_stand.dae" />
          </geometry>
      </visual>
      <collision name="rpi_4_stand_collision">
        <origin xyz="0.045 0 0.017" rpy="0 0 ${pi/2}"/>
        <geometry>
          <box size="0.098 0.065 0.034"/>
        </geometry>
      </collision>

      <!-- Raspberry Pi -->
      <visual name="rpi_4_visual">
        <origin xyz="0.046 0.00245 0.033" rpy="0 0 ${pi/2}"/>
        <geometry>
          <mesh filename="package://robot_description/meshes/rpi_4.dae"/>
        </geometry>
      </visual>
      <collision name="rpi_4_collision">
        <origin xyz="0.047 0.005 0.041" rpy="0 0 ${pi/2}"/>
        <geometry>
          <box size="0.09 0.06 0.02"/>
        </geometry>
      </collision>

      <!-- Power bank stand -->
      <visual name="power_bank_stand_visual">
        <origin xyz="0.138 0.015 0.031" rpy="${pi} 0 ${pi}"/>
        <geometry>
          <mesh filename="package://robot_description/meshes/power_bank_stand.dae"/>
        </geometry>
      </visual>
      <collision name="power_bank_stand_collision">
        <origin xyz="0.138 0 0.0085" rpy="0 0 ${pi/2}"/>
        <geometry>
          <box size="0.098 0.065 0.015"/>
        </geometry>
      </collision>

      <!-- Power bank -->
      <visual name="power_bank_visual">
        <origin xyz="0.1685 0.04775 0.015" rpy="0 0 ${pi/2}"/>
        <geometry>
          <mesh filename="package://robot_description/meshes/power_bank.dae"/>
        </geometry>
      </visual>
      <collision name="power_bank_collision">
        <origin xyz="0.138 0 0.025" rpy="0 0 ${pi/2}"/>
        <geometry>
          <box size="0.096 0.062 0.02"/>
        </geometry>
      </collision>
      
      <!-- Rplidar stand -->
      <visual name="rplidar_stand_visual">
        <origin xyz="0.138 0.015 0.017" rpy="0 0 ${-2*pi}"/> 
        <geometry>
          <mesh filename="package://robot_description/meshes/rplidar_stand.dae"/>
        </geometry>
      </visual>
      <collision name="rplidar_stand_collision">
        <origin xyz="0.138 0 0.04" rpy="0 0 ${pi/2}"/>
        <geometry>
          <box size="0.098 0.065 0.015"/>
        </geometry>
      </collision>

      <!-- Rplidar base -->
      <visual name="rplidar_base_visual">
        <origin xyz="0.13985 0.0087 0.037" rpy="0 0 ${-pi/2}"/>
          <geometry>
            <mesh filename="package://robot_description/meshes/rplidar_base.dae"/>
          </geometry>
        </visual>
      <collision name="rplidar_base_collision">
        <origin xyz="0.138 0 0.056" rpy="0 0 ${-pi/2}"/>
        <geometry>
          <box size="0.11 0.072 0.035"/>
        </geometry>
      </collision>

      <!-- Camera mount -->
      <visual name="camera_mount_visual">
        <origin xyz="0.16 0.0335 0.001" rpy="0 0 ${pi}"/>
          <geometry>
            <mesh filename="package://robot_description/meshes/rpi_camera_mount.dae"/>
          </geometry>
      </visual>
      <collision name="camera_mount_collision">
        <origin xyz="0.197 0.0 0.032" rpy="${pi/2} 0 ${pi/2}"/>
        <geometry>
          <box size="0.048 0.06 0.033"/>
        </geometry>
      </collision>

    <xacro:box_inertia mass="0.864" length="${base_length}" width="${base_width}" height="${base_height}">
      <origin xyz="0.105 0 0.0175" rpy="0 0 0"/>
    </xacro:box_inertia>
  </link>

  <!-- Left wheel -->
  <link name="wheel_left_link">
    <visual>
        <geometry>
          <mesh filename="package://robot_description/meshes/right_wheel.dae" />
        </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 -0.0065" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${wheel_radius}"/>
      </geometry>
    </collision>

    <xacro:cylinder_inertia mass="${wheel_mass}" length="${wheel_height}" radius="${wheel_radius}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:cylinder_inertia>
  </link>

  <joint name="wheel_left_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_left_link"/>
    <origin xyz="0.133 0.065 -${wheel_zoff}" rpy="-${pi/2} 0 ${pi}"/>
    <axis xyz="0 0 -1"/>
  </joint>

  <!-- Right wheel -->
  <link name="wheel_right_link">
    <visual>
      <geometry>
        <mesh filename="package://robot_description/meshes/right_wheel.dae"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 -0.0065" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${wheel_radius}"/>
      </geometry>
    </collision>

    <xacro:cylinder_inertia mass="${wheel_mass}" length="${wheel_height}" radius="${wheel_radius}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:cylinder_inertia>
  </link>

  <joint name="wheel_right_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_right_link"/>
    <origin xyz="0.133 -0.065 -${wheel_zoff}" rpy="${pi/2} 0 ${-pi}"/>
    <axis xyz="0 0 1"/>
  </joint>

  <!-- Caster wheel -->
  <link name="caster_wheel">
    <visual>
      <geometry>
        <mesh filename="package://robot_description/meshes/caster_wheel.dae"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 -0.001" rpy="0 0 ${pi/2}"/>
      <geometry>
        <sphere radius="0.015"/>
      </geometry>
    </collision>

    <xacro:sphere_inertia mass="0.033" radius="0.025">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:sphere_inertia>
  </link>

  <joint name="caster_wheel_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_wheel"/>
    <origin xyz="0.028 0 -0.031" rpy="0 0 ${pi/2}"/>
  </joint>

	<link name="lidar_link">
        <visual>
            <origin xyz="0 -0.0009 -0.011" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://robot_description/meshes/rplidar_top.dae"/>
            </geometry>
        </visual> 
        <collision>
            <origin xyz="0 -0.0028 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.037" length="0.021"/>
            </geometry>
        </collision>
         <xacro:cylinder_inertia mass="0.07" length="0.021" radius="0.037">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:cylinder_inertia>
   </link>

    <joint name="lidar_joint" type="fixed">
        <parent link="base_link"/>
        <child link="lidar_link"/>
        <origin xyz="0.1385 0.0095 0.08" rpy="0 0 ${-pi}"/>
        <axis xyz="0 0 1"/>
    </joint>
	
	  <!-- Imu sensor  -->
  <link name="imu_link">
    <visual name="imu_visual">
      <geometry>
        <mesh filename="package://lidarbot_description/meshes/MPU6050.dae"/>
      </geometry>
    </visual>
  </link>

  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0.045 0 0.0175" rpy="0 0 0"/> 
  </joint>

  <!-- <gazebo reference="caster_wheel">
    <mu1 value="0.001"/>
    <mu2 value="0.001"/>
  </gazebo>

  <gazebo reference="wheel_left_link">
    <mu1 value="1.16"/>
    <mu2 value="1.16"/>
  </gazebo>

  <gazebo reference="wheel_right_link">
    <mu1 value="1.16"/>
    <mu2 value="1.16"/>
  </gazebo> -->

</robot>
