controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: false

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    wheel_controller:
      type: diff_drive_controller/DiffDriveController

    imu_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster 


wheel_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    use_stamped_vel: false
    # controllers and interfaces linked by parameters <...>_names, such as left_wheel_names, right_wheel_names
    # left_wheel_names, right_wheel_names must be matched with the joint names in ros2_control.xacro
    # no need to be matched the joint names in robot_core.xacro, but should be
    left_wheel_names: ['wheel_left_joint']
    right_wheel_names: ['wheel_right_joint']
    publish_rate: 50.0
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

    wheel_radius: 0.0335
    wheel_separation: 0.134
    # left_wheel_radius_multiplier: 1.0
    # right_wheel_radius_multiplier: 1.0
    # wheel_separation_multiplier: 1.0

    cmd_vel_timeout: 0.25
    base_frame_id: base_footprint
    publish_limited_velocity: true
    publish_wheel_data: true
    enable_odom_tf: true

    # linear:
    #   x:
    #     has_velocity_limits: true
    #     max_velocity: 1.0
    #     min_velocity: -0.5
    #     has_acceleration_limits: true
    #     max_acceleration: 0.8
    #     min_acceleration: -0.4
    #     has_jerk_limits: false

    # angular:
    #   z:
    #     has_velocity_limits: true
    #     max_velocity: 1.7
    #     min_velocity: -1.7
    #     has_acceleration_limits: true
    #     max_acceleration: 1.5
    #     min_acceleration: -1.5
    #     has_jerk_limits: false

    # publish_rate: 50.0 # Has to be a double otherwise errors are encountered

    # base_frame_id: base_footprint

    # left_wheel_names: ['wheel_left_joint']
    # right_wheel_names: ['wheel_right_joint']
    # wheel_separation: 0.134
    # wheel_radius: 0.0335

    # # Obtained from https://wiki.ros.org/diff_drive_controller
    # pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    # twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0] 

    # # Whether the input has a time stamp or not
    # use_stamped_vel: false

    # # Odometry fused with IMU is published by robot_localization, so no need to publish a TF
    # # based on encoders alone (https://wiki.ros.org/diff_drive_controller)
    # enable_odom_tf: false


imu_broadcaster:
  ros__parameters:
    sensor_name: mpu6050
    frame_id: imu_link
   
   # 500 data points used to calculated covariances
    static_covariance_orientation: [1.12635e-05, 0.0, 0.0, 2.48434e-06, 0.0, 0.0, 8.12248e-09, 0.0, 0.0]
    static_covariance_angular_velocity: [7.34887e-07, 0.0, 0.0, 4.40435e-07, 0.0, 0.0, 4.86794e-07, 0.0, 0.0]
    static_covariance_linear_acceleration: [0.000347089, 0.0, 0.0, 0.0020293, 0.0, 0.0, 0.000508561, 0.0, 0.0]